import geopandas as gpd
import pandas as pd
import numpy as np
from pathlib import Path
import warnings

warnings.filterwarnings('ignore', category=pd.errors.PerformanceWarning)

def get_extreme_rainfall(rainfall_csv):
    """Finds the maximum rainfall event to pair with historical spatial floods."""
    if not rainfall_csv.exists():
        print(f"  - Warning: {rainfall_csv} not found. Rainfall features will be 0.")
        return {col: 0 for col in ['rainfall_24h', 'rainfall_3day', 'rainfall_72h', 'rainfall_7day', 'rainfall_30day']}
        
    df = pd.read_csv(rainfall_csv)
    # Get the row with the maximum 24h rainfall
    extreme_event = df.loc[df['rainfall_24h'].idxmax()]
    print(f"  - Selected Extreme Rainfall Event Date: {extreme_event['date']}")
    
    return {
        'rainfall_24h': extreme_event['rainfall_24h'],
        'rainfall_3day': extreme_event['rainfall_3day'],
        'rainfall_72h': extreme_event['rainfall_72h'],
        'rainfall_7day': extreme_event['rainfall_7day'],
        'rainfall_30day': extreme_event['rainfall_30day']
    }

def combine_and_validate():
    # Input Paths
    grid_path = Path("data/processed/grid/chennai_grid.geojson")
    terrain_path = Path("data/processed/elevation/terrain_features.geojson")
    roads_path = Path("data/processed/roads/road_features.geojson")
    water_path = Path("data/processed/water_bodies/water_distance_features.geojson")
    land_use_path = Path("data/processed/land_use/land_use_features.geojson")
    labels_path = Path("data/processed/flood_history/flood_labels.geojson")
    rainfall_path = Path("data/processed/rainfall/rainfall_features.csv")

    # Output Paths
    out_dir_final = Path("data/final")
    out_dir_final.mkdir(parents=True, exist_ok=True)
    out_geojson = Path("data/processed/grid/chennai_grid_with_features.geojson")
    out_csv = out_dir_final / "chennai_flood_training_dataset.csv"

    print("Loading component datasets...")
    # Base grid
    master_grid = gpd.read_file(grid_path, engine="pyogrio")
    
    # Helper to drop geometry for merging
    def load_for_merge(path):
        if not path.exists():
            print(f"  - Missing: {path.name}")
            return None
        gdf = gpd.read_file(path, engine="pyogrio")
        return pd.DataFrame(gdf.drop(columns=['geometry']))

    terrain_df = load_for_merge(terrain_path)
    roads_df = load_for_merge(roads_path)
    water_df = load_for_merge(water_path)
    landuse_df = load_for_merge(land_use_path)
    labels_df = load_for_merge(labels_path)

    print("Merging features sequentially...")
    # Merge all available datasets sequentially on cell_id
    if terrain_df is not None:
        master_grid = master_grid.merge(terrain_df, on='cell_id', how='left')
    if roads_df is not None:
        master_grid = master_grid.merge(roads_df, on='cell_id', how='left')
    if water_df is not None:
        master_grid = master_grid.merge(water_df, on='cell_id', how='left')
    if landuse_df is not None:
        master_grid = master_grid.merge(landuse_df, on='cell_id', how='left')
    if labels_df is not None:
        master_grid = master_grid.merge(labels_df, on='cell_id', how='left')

    # Add rainfall features
    print("Applying rainfall features...")
    rainfall_data = get_extreme_rainfall(rainfall_path)
    for col, val in rainfall_data.items():
        master_grid[col] = val

    # Fill NaNs generated by left joins
    master_grid = master_grid.fillna(0)

    # ---------------------------------------------------------
    # VALIDATION PHASE
    # ---------------------------------------------------------
    print("\n--- VALIDATING FINAL DATASET ---")
    
    # 1. Missing Values
    null_counts = master_grid.drop(columns=['geometry']).isnull().sum().sum()
    print(f"Total Missing Values: {null_counts}")
    if null_counts > 0:
        print("WARNING: Dataset contains missing values. Check merge logic.")

    # 2. Infinite Values
    numeric_cols = master_grid.select_dtypes(include=[np.number]).columns
    inf_counts = np.isinf(master_grid[numeric_cols]).sum().sum()
    print(f"Total Infinite Values: {inf_counts}")
    if inf_counts > 0:
        print("WARNING: Dataset contains infinite values. Replacing with 0.")
        master_grid.replace([np.inf, -np.inf], 0, inplace=True)

    # 3. Geometry and CRS
    print(f"CRS Valid: {master_grid.crs == 'EPSG:4326'}")
    print(f"Invalid Geometries: {(~master_grid.geometry.is_valid).sum()}")
    
    # 4. Duplicate Cell IDs
    dup_ids = master_grid['cell_id'].duplicated().sum()
    print(f"Duplicate cell_ids: {dup_ids}")
    
    # 5. Class Balance
    if 'flood_label' in master_grid.columns:
        flooded = (master_grid['flood_label'] == 1).sum()
        safe = (master_grid['flood_label'] == 0).sum()
        print(f"Class Balance: {flooded} Flooded (1) vs {safe} Non-Flooded (0)")
        if flooded == 0:
            print("CRITICAL WARNING: No flooded labels in the final dataset!")

    # ---------------------------------------------------------
    # EXPORT PHASE
    # ---------------------------------------------------------
    print("\nExporting datasets...")
    
    # Save the master spatial file
    master_grid.to_file(out_geojson, driver="GeoJSON", engine="pyogrio")
    print(f"Saved master spatial grid to {out_geojson}")

    # Prepare and save ML-ready CSV (drop geometry)
    csv_df = pd.DataFrame(master_grid.drop(columns=['geometry']))
    
    # Ensure all requested ML columns exist
    required_cols = [
        'cell_id', 'centroid_latitude', 'centroid_longitude', 
        'elevation_mean', 'elevation_min', 'elevation_max', 
        'slope_mean', 'slope_min', 'slope_max', 
        'rainfall_24h', 'rainfall_3day', 'rainfall_72h', 'rainfall_7day', 'rainfall_30day', 
        'distance_to_water_m', 'distance_to_river_m', 'distance_to_drain_m', 
        'drainage_length_m', 'drainage_density', 
        'built_up_percentage', 'water_percentage', 'vegetation_percentage', 
        'cropland_percentage', 'bare_land_percentage', 
        'historical_flood_count', 'flood_label'
    ]
    
    missing_cols = [c for c in required_cols if c not in csv_df.columns]
    if missing_cols:
        print(f"WARNING: The following required ML columns are missing: {missing_cols}")
    
    csv_df.to_csv(out_csv, index=False)
    print(f"Saved Machine Learning CSV dataset ({len(csv_df)} rows, {len(csv_df.columns)} columns) to {out_csv}")

if __name__ == "__main__":
    combine_and_validate()